version: '3.8'

services:
  device-health-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"
